apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ftpsync-cm
data:
  ftpsync.conf: |
    {{- .Values.crontab.config | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-cm
data:
  nginx.conf: |
    {{- .Values.web.config | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-crontab-cm
data:
  crontabEntry: |
    {{- .Values.crontab.entry | nindent 4 }}
