apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerconfig-ghcr
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "0"
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /k8s/ghcr_repo_creds
  target:
    template:
      type: kubernetes.io/dockerconfigjson
